import {distanceYards,interpolateGeo} from './distance.js';
import {recommendClub} from './caddie.js';
import {collectCoordinates,createProjection,renderGeoJSON,featureType} from './map.js';

const COURSE_URL='./course_data/cog_hill_18.json';
const TERRAIN_URL='./course_data/cog_hill_18_elevation.json';
let clubs=[{name:'Driver',carry:215,total:230},{name:'3-Wood',carry:195,total:210},{name:'5-Iron',carry:165,total:170},{name:'7-Iron',carry:145,total:150},{name:'9-Iron',carry:125,total:130},{name:'PW',carry:105,total:110},{name:'SW',carry:75,total:80}];
let course,geojson,holeGeoJSON,projection,tee,pin,ball,hazards=[],strokeCount=0,holed=false;
const $=id=>document.getElementById(id), props=f=>f?.properties||{};
function centroid(ring){const pts=ring.length>1?ring.slice(0,-1):ring;return{lng:pts.reduce((s,p)=>s+p[0],0)/pts.length,lat:pts.reduce((s,p)=>s+p[1],0)/pts.length}}
function geometryCenter(f){if(!f?.geometry)return null;if(f.geometry.type==='Point'){const[lng,lat]=f.geometry.coordinates;return{lng,lat}}const ring=f.geometry.type==='Polygon'?f.geometry.coordinates[0]:f.geometry.type==='MultiPolygon'?f.geometry.coordinates[0][0]:null;return ring?centroid(ring):null}
function text(f){return Object.values(props(f)).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase()}
function isHole18(f){const p=props(f);const n=String(p.ref??p.hole??p.hole_number??p.number??'');return n==='18'||/\bhole\s*18\b/.test(text(f))}
function getFeatures(type,source=geojson){return(source.features||[]).filter(f=>featureType(f)===type)}
function findHole18Line(){return(geojson.features||[]).find(f=>f.geometry?.type==='LineString'&&isHole18(f)&&String(props(f).golf||'').toLowerCase()==='hole')||(geojson.features||[]).find(f=>f.geometry?.type==='LineString'&&isHole18(f))}
function lineCoords(f){return f?.geometry?.type==='LineString'?f.geometry.coordinates:[]}
function lineEndpoints(f){const c=lineCoords(f);if(!c.length)return null;return[{lng:c[0][0],lat:c[0][1]},{lng:c.at(-1)[0],lat:c.at(-1)[1]}]}
function distanceToLineFeature(point,line){return Math.min(...lineCoords(line).map(([lng,lat])=>distanceYards(point,{lng,lat})))}
function deriveHole18(){const line=findHole18Line();if(!line)throw Error('Hole 18 playing line was not found');const ends=lineEndpoints(line);const greens=getFeatures('green'),tees=getFeatures('tee');const green=greens.map(f=>({f,c:geometryCenter(f)})).filter(x=>x.c).sort((a,b)=>Math.min(distanceYards(ends[0],a.c),distanceYards(ends[1],a.c))-Math.min(distanceYards(ends[0],b.c),distanceYards(ends[1],b.c)))[0];if(!green)throw Error('Hole 18 green was not found');const pin=green.c;const teeEnd=distanceYards(ends[0],pin)>distanceYards(ends[1],pin)?ends[0]:ends[1];const teeCandidates=tees.map(f=>({f,c:geometryCenter(f)})).filter(x=>x.c&&distanceYards(x.c,teeEnd)<130).sort((a,b)=>distanceYards(a.c,teeEnd)-distanceYards(b.c,teeEnd));const tee=teeCandidates[0]?.c||teeEnd;const nearby=(geojson.features||[]).filter(f=>{const type=featureType(f);if(!['fairway','green','tee','bunker','water'].includes(type))return false;const c=geometryCenter(f);return c&&distanceToLineFeature(c,line)<180});return{tee,pin,line,features:[...nearby,line]}}
function polyToScreen(f){const ring=f.geometry.type==='Polygon'?f.geometry.coordinates[0]:f.geometry.type==='MultiPolygon'?f.geometry.coordinates[0][0]:null;return ring?ring.map(([lng,lat])=>{const p=projection.project({lat,lng});return[p.x,p.y]}):[]}
function updateStrokeUI(){$('strokeRow').textContent=`Shot ${strokeCount+1} · Par ${course.par}`;$('strokeInput').value=strokeCount}
function drawTarget(target,from){const a=projection.project(from),b=projection.project(target);[['shotLine',{x1:a.x,y1:a.y,x2:b.x,y2:b.y}],['targetDot',{cx:b.x,cy:b.y}],['ball',{cx:a.x,cy:a.y}]].forEach(([id,attrs])=>Object.entries(attrs).forEach(([k,v])=>$(id).setAttribute(k,v)))}
function recommend(){const remaining=distanceYards(ball,pin),from=projection.project(ball),pinPx=projection.project(pin);$('remainYards').textContent=Math.round(remaining);$('statusLine').style.display='none';if(remaining<20){$('recClub').textContent='Putter';$('shotYards').textContent=Math.round(remaining*3);$('shotUnit').textContent=' foot putt (approx.)';drawTarget(pin,ball);return}$('shotUnit').textContent=' yard shot';const rec=recommendClub({remainingYards:remaining,clubs,from,pin:pinPx,hazards,projectAlongShot:f=>projection.project(interpolateGeo(ball,pin,f))});$('recClub').textContent=rec.club.name;$('shotYards').textContent=Math.round(Math.min(rec.club.total,remaining));if(rec.reason){$('statusLine').textContent=rec.reason;$('statusLine').style.display='block'}drawTarget(projection.unproject(rec.target),ball)}
function renderClubInputs(){const c=$('clubInputs');c.innerHTML='<span></span><span class="club-head">Carry</span><span class="club-head">Total</span>';clubs.forEach((club,i)=>{const l=document.createElement('label');l.textContent=club.name;c.appendChild(l);['carry','total'].forEach(key=>{const input=document.createElement('input');input.type='number';input.value=club[key];input.addEventListener('input',e=>{clubs[i][key]=+e.target.value||0;recommend()});c.appendChild(input)})})}
function finishHole(n){holed=true;strokeCount=n;$('strokeRow').textContent=`Holed in ${n}`;$('strokeInput').value=n;$('recClub').textContent='Holed out';$('shotYards').textContent=n;$('shotUnit').textContent=' total strokes';$('remainYards').textContent=0}
function bind(){const svg=$('hole');svg.addEventListener('click',e=>{if(holed)return;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());ball=projection.unproject({x:q.x,y:q.y});strokeCount++;if(distanceYards(ball,pin)<2)return finishHole(strokeCount);updateStrokeUI();recommend()});$('resetBtn').onclick=()=>{ball={...tee};strokeCount=0;holed=false;updateStrokeUI();recommend()};$('holedBtn').onclick=()=>finishHole(Math.max(1,strokeCount+1))}
async function init(){course=await fetch(COURSE_URL).then(r=>r.json());const terrain=await fetch(TERRAIN_URL).then(r=>r.json());$('courseName').textContent=course.course;$('holeMeta').textContent=`Hole ${course.hole} · Par ${course.par} · Black tee ${course.yardages.Black} yd`;$('terrainStatus').textContent=terrain.samples.length?'Loaded':'Awaiting real elevation samples';geojson=await fetch(course.geometry.geojson).then(r=>r.json());const h=deriveHole18();tee=h.tee;pin=h.pin;holeGeoJSON={type:'FeatureCollection',features:h.features};const coords=collectCoordinates(holeGeoJSON);coords.push([tee.lng,tee.lat],[pin.lng,pin.lat]);projection=createProjection(coords);renderGeoJSON($('hole'),holeGeoJSON,projection);ball={...tee};hazards=[...getFeatures('water',holeGeoJSON),...getFeatures('bunker',holeGeoJSON)].map(f=>({name:featureType(f),poly:polyToScreen(f)})).filter(h=>h.poly.length);const t=projection.project(tee),g=projection.project(pin);$('teeMarker').setAttribute('x',t.x-5);$('teeMarker').setAttribute('y',t.y-4);$('pin').setAttribute('cx',g.x);$('pin').setAttribute('cy',g.y);renderClubInputs();updateStrokeUI();bind();recommend()}
init().catch(err=>{$('statusLine').textContent=`Map data error: ${err.message}`;$('statusLine').style.display='block';console.error(err)});