import {distanceYards,interpolateGeo} from './distance.js';
import {recommendClub} from './caddie.js';
import {collectCoordinates,createProjection,renderGeoJSON,featureType} from './map.js';

const COURSE_URL='./course_data/cog_hill_18.json';
const TERRAIN_URL='./course_data/cog_hill_18_elevation.json';
let clubs=[{name:'Driver',carry:215,total:230},{name:'3-Wood',carry:195,total:210},{name:'5-Iron',carry:165,total:170},{name:'7-Iron',carry:145,total:150},{name:'9-Iron',carry:125,total:130},{name:'PW',carry:105,total:110},{name:'SW',carry:75,total:80}];
let course,geojson,projection,tee,pin,ball,hazards=[],strokeCount=0,holed=false;
const $=id=>document.getElementById(id);
const props=f=>f?.properties||{};
function centroid(ring){const pts=ring.length>1?ring.slice(0,-1):ring;return{lng:pts.reduce((s,p)=>s+p[0],0)/pts.length,lat:pts.reduce((s,p)=>s+p[1],0)/pts.length}}
function geometryCenter(f){if(!f?.geometry)return null;if(f.geometry.type==='Point'){const [lng,lat]=f.geometry.coordinates;return{lng,lat}}const ring=f.geometry.type==='Polygon'?f.geometry.coordinates[0]:f.geometry.type==='MultiPolygon'?f.geometry.coordinates[0][0]:null;return ring?centroid(ring):null}
function text(f){return Object.values(props(f)).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase()}
function holeNumber(f){const p=props(f);return String(p.hole??p.ref??p.hole_number??p.holenumber??p.number??'')}
function isHole18(f){const h=holeNumber(f);return h==='18'||/\bhole\s*18\b/.test(text(f))}
function getFeatures(type){return (geojson.features||[]).filter(f=>featureType(f)===type)}
function featuresNear(point,features,maxYards=180){return features.filter(f=>{const c=geometryCenter(f);return c&&distanceYards(point,c)<=maxYards})}
function findHole18Line(){const lines=(geojson.features||[]).filter(f=>['LineString','MultiLineString'].includes(f.geometry?.type));return lines.find(isHole18)||lines.find(f=>/playing|hole/.test(text(f))&&isHole18(f))||null}
function lineEndpoints(f){if(!f)return null;const coords=f.geometry.type==='LineString'?f.geometry.coordinates:f.geometry.coordinates[0];if(!coords?.length)return null;const a={lng:coords[0][0],lat:coords[0][1]},z=coords[coords.length-1];return[a,{lng:z[0],lat:z[1]}]}
function deriveTeeAndPin(){const greens=getFeatures('green'),tees=getFeatures('tee');const green18=greens.find(isHole18);const tee18=tees.filter(isHole18);if(green18&&tee18.length)return{tee:geometryCenter(tee18[0]),pin:geometryCenter(green18)};const line=findHole18Line(),ends=lineEndpoints(line);if(ends){const [a,b]=ends;const nearestGreen=greens.map(f=>({f,c:geometryCenter(f)})).filter(x=>x.c).sort((x,y)=>Math.min(distanceYards(a,x.c),distanceYards(b,x.c))-Math.min(distanceYards(a,y.c),distanceYards(b,y.c)))[0];if(nearestGreen){const g=nearestGreen.c;return distanceYards(a,g)<distanceYards(b,g)?{tee:b,pin:g}:{tee:a,pin:g}}return{tee:a,pin:b}}if(green18)return{pin:geometryCenter(green18),tee:null};return{tee:null,pin:null}}
function polyToScreen(f){const ring=f.geometry.type==='Polygon'?f.geometry.coordinates[0]:f.geometry.type==='MultiPolygon'?f.geometry.coordinates[0][0]:null;if(!ring)return[];return ring.map(([lng,lat])=>{const p=projection.project({lat,lng});return[p.x,p.y]})}
function scoreLabel(d){if(d<=-2)return'eagle or better';if(d===-1)return'birdie';if(d===0)return'par';if(d===1)return'bogey';if(d===2)return'double bogey';return`${d} over par`}
function updateStrokeUI(){$('strokeRow').textContent=`Shot ${strokeCount+1} · Par ${course.par}`;$('strokeInput').value=strokeCount}
function drawTarget(target,from){const a=projection.project(from),b=projection.project(target);for(const [id,attrs] of [['shotLine',{x1:a.x,y1:a.y,x2:b.x,y2:b.y}],['targetDot',{cx:b.x,cy:b.y}],['ball',{cx:a.x,cy:a.y}]])Object.entries(attrs).forEach(([k,v])=>$(id).setAttribute(k,v))}
function recommend(){const remaining=distanceYards(ball,pin),from=projection.project(ball),pinPx=projection.project(pin);$('remainYards').textContent=Math.round(remaining);$('statusLine').style.display='none';if(remaining<20){$('recClub').textContent='Putter';$('shotYards').textContent=Math.round(remaining*3);$('shotUnit').textContent=' foot putt (approx.)';drawTarget(pin,ball);return}$('shotUnit').textContent=' yard shot';const rec=recommendClub({remainingYards:remaining,clubs,from,pin:pinPx,hazards,projectAlongShot:f=>projection.project(interpolateGeo(ball,pin,f))});$('recClub').textContent=rec.club.name;$('shotYards').textContent=Math.round(Math.min(rec.club.total,remaining));if(rec.reason){$('statusLine').textContent=rec.reason;$('statusLine').style.display='block'}drawTarget(projection.unproject(rec.target),ball)}
function renderClubInputs(){const c=$('clubInputs');c.innerHTML='<span></span><span class="club-head">Carry</span><span class="club-head">Total</span>';clubs.forEach((club,i)=>{const l=document.createElement('label');l.textContent=club.name;c.appendChild(l);['carry','total'].forEach(key=>{const input=document.createElement('input');input.type='number';input.value=club[key];input.addEventListener('input',e=>{clubs[i][key]=+e.target.value||0;recommend()});c.appendChild(input)})})}
function finishHole(n){holed=true;strokeCount=n;$('strokeRow').textContent=`Holed in ${n} · ${scoreLabel(n-course.par)}`;$('strokeInput').value=n;$('recClub').textContent='Holed out';$('shotYards').textContent=n;$('shotUnit').textContent=' total strokes';$('remainYards').textContent=0}
function bind(){const svg=$('hole');svg.addEventListener('click',e=>{if(holed)return;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());ball=projection.unproject({x:q.x,y:q.y});strokeCount++;if(distanceYards(ball,pin)<2){finishHole(strokeCount);return}updateStrokeUI();recommend()});$('strokeInput').addEventListener('input',e=>{if(!holed){strokeCount=Math.max(0,+e.target.value||0);updateStrokeUI()}});$('holedBtn').onclick=()=>{if(!holed)finishHole(Math.max(1,+$('strokeInput').value||strokeCount||1))};$('resetBtn').onclick=()=>{ball={...tee};strokeCount=0;holed=false;updateStrokeUI();recommend()}}
async function init(){course=await fetch(COURSE_URL).then(r=>r.json());const terrain=await fetch(TERRAIN_URL).then(r=>r.json());$('courseName').textContent=course.course;$('holeMeta').textContent=`Hole ${course.hole} · Par ${course.par} · Black tee ${course.yardages.Black} yd`;$('terrainStatus').textContent=terrain.samples.length?'Loaded':'Awaiting real elevation samples';geojson=await fetch(course.geometry.geojson).then(r=>{if(!r.ok)throw Error('Course geometry failed to load');return r.json()});const coords=collectCoordinates(geojson);if(!coords.length)throw Error('Course geometry contains no coordinates');projection=createProjection(coords);renderGeoJSON($('hole'),geojson,projection);({tee,pin}=deriveTeeAndPin());if(!tee||!pin)throw Error('Could not locate Hole 18 tee and green in mapped course data');ball={...tee};const localHazards=[...getFeatures('water'),...getFeatures('bunker')];hazards=localHazards.filter(f=>{const c=geometryCenter(f);return c&&Math.min(distanceYards(tee,c),distanceYards(pin,c))<650}).map(f=>({name:featureType(f),poly:polyToScreen(f)})).filter(h=>h.poly.length);const t=projection.project(tee),g=projection.project(pin);$('teeMarker').setAttribute('x',t.x-5);$('teeMarker').setAttribute('y',t.y-4);$('pin').setAttribute('cx',g.x);$('pin').setAttribute('cy',g.y);renderClubInputs();updateStrokeUI();bind();recommend()}
init().catch(err=>{$('statusLine').textContent=`Map data error: ${err.message}`;$('statusLine').style.display='block';console.error(err)});
