import {distanceYards,interpolateGeo} from './distance.js';
import {recommendClub} from './caddie.js';
import {collectCoordinates,createProjection,renderGeoJSON,featureType} from './map.js';

const COURSE_URL='./course_data/cog_hill_18.json';
const TERRAIN_URL='./course_data/cog_hill_18_elevation.json';
let clubs=[{name:'Driver',carry:215,total:230},{name:'3-Wood',carry:195,total:210},{name:'5-Iron',carry:165,total:170},{name:'7-Iron',carry:145,total:150},{name:'9-Iron',carry:125,total:130},{name:'PW',carry:105,total:110},{name:'SW',carry:75,total:80}];
let course,geojson,holeGeoJSON,projection,tee,pin,ball,hazards=[],strokeCount=0,holed=false;
const $=id=>document.getElementById(id),props=f=>f?.properties||{};
function centroid(ring){const pts=ring.length>1?ring.slice(0,-1):ring;return{lng:pts.reduce((s,p)=>s+p[0],0)/pts.length,lat:pts.reduce((s,p)=>s+p[1],0)/pts.length}}
function geometryCenter(f){if(!f?.geometry)return null;if(f.geometry.type==='Point'){const[lng,lat]=f.geometry.coordinates;return{lng,lat}}const ring=f.geometry.type==='Polygon'?f.geometry.coordinates[0]:f.geometry.type==='MultiPolygon'?f.geometry.coordinates[0][0]:null;return ring?centroid(ring):null}
function flattenText(v){if(v==null)return'';if(typeof v==='object')return Object.values(v).map(flattenText).join(' ');return String(v)}
function text(f){return flattenText(props(f)).toLowerCase()}
function is18(f){const t=text(f);return /(^|\D)18(\D|$)/.test(t)||['18',18].includes(props(f).ref)||['18',18].includes(props(f).hole)||['18',18].includes(props(f).number)}
function getFeatures(type,source=geojson){return(source.features||[]).filter(f=>featureType(f)===type)}
function allLineFeatures(){return(geojson.features||[]).filter(f=>['LineString','MultiLineString'].includes(f.geometry?.type))}
function lineCoords(f){if(f?.geometry?.type==='LineString')return f.geometry.coordinates;if(f?.geometry?.type==='MultiLineString')return f.geometry.coordinates.flat();return[]}
function lineEndpoints(f){const c=lineCoords(f);return c.length?[{lng:c[0][0],lat:c[0][1]},{lng:c.at(-1)[0],lat:c.at(-1)[1]}]:null}
function lineLengthYards(f){const c=lineCoords(f);let d=0;for(let i=1;i<c.length;i++)d+=distanceYards({lng:c[i-1][0],lat:c[i-1][1]},{lng:c[i][0],lat:c[i][1]});return d}
function findHole18Line(){const lines=allLineFeatures();const explicit=lines.filter(is18);if(explicit.length)return explicit.sort((a,b)=>Math.abs(lineLengthYards(a)-course.yardages.Black)-Math.abs(lineLengthYards(b)-course.yardages.Black))[0];const golfLines=lines.filter(f=>/hole|golf/.test(text(f)));if(golfLines.length>=18)return golfLines.sort((a,b)=>lineLengthYards(b)-lineLengthYards(a))[17];return null}
function distanceToLineFeature(point,line){const c=lineCoords(line);return c.length?Math.min(...c.map(([lng,lat])=>distanceYards(point,{lng,lat}))):Infinity}
function nearestFeatureTo(point,features){return features.map(f=>({f,c:geometryCenter(f)})).filter(x=>x.c).sort((a,b)=>distanceYards(point,a.c)-distanceYards(point,b.c))[0]}
function deriveHole18(){let line=findHole18Line();const greens=getFeatures('green'),tees=getFeatures('tee');if(line){const ends=lineEndpoints(line);const g0=nearestFeatureTo(ends[0],greens),g1=nearestFeatureTo(ends[1],greens);const green=(!g1||g0&&distanceYards(ends[0],g0.c)<=distanceYards(ends[1],g1.c))?g0:g1;if(!green)throw Error('Mapped course has no green polygons');pin=green.c;const teeEnd=distanceYards(ends[0],pin)>distanceYards(ends[1],pin)?ends[0]:ends[1];tee=nearestFeatureTo(teeEnd,tees)?.c||teeEnd}else{
  // Schema fallback: infer the par-4 black-tee hole by finding tee/green pairs near the official 494-yard length.
  const gs=greens.map(f=>({f,c:geometryCenter(f)})).filter(x=>x.c),ts=tees.map(f=>({f,c:geometryCenter(f)})).filter(x=>x.c);let best=null;for(const t of ts)for(const g of gs){const d=distanceYards(t.c,g.c);const score=Math.abs(d-course.yardages.Black);if(d>330&&d<620&&(!best||score<best.score))best={t,g,score,d}}if(!best)throw Error('Could not infer Hole 18 from mapped tees and greens');tee=best.t.c;pin=best.g.c;
 }
 const nearby=(geojson.features||[]).filter(f=>{const type=featureType(f);if(!['fairway','green','tee','bunker','water'].includes(type))return false;const c=geometryCenter(f);if(!c)return false;const corridor=line?distanceToLineFeature(c,line):Math.min(distanceYards(c,tee),distanceYards(c,pin));return corridor<220});return{tee,pin,line,features:line?[...nearby,line]:nearby}}
function polyToScreen(f){const ring=f.geometry.type==='Polygon'?f.geometry.coordinates[0]:f.geometry.type==='MultiPolygon'?f.geometry.coordinates[0][0]:null;return ring?ring.map(([lng,lat])=>{const p=projection.project({lat,lng});return[p.x,p.y]}):[]}
function updateStrokeUI(){$('strokeRow').textContent=`Shot ${strokeCount+1} · Par ${course.par}`;$('strokeInput').value=strokeCount}
function drawTarget(target,from){const a=projection.project(from),b=projection.project(target);[['shotLine',{x1:a.x,y1:a.y,x2:b.x,y2:b.y}],['targetDot',{cx:b.x,cy:b.y}],['ball',{cx:a.x,cy:a.y}]].forEach(([id,attrs])=>Object.entries(attrs).forEach(([k,v])=>$(id).setAttribute(k,v)))}
function recommend(){const remaining=distanceYards(ball,pin),from=projection.project(ball),pinPx=projection.project(pin);$('remainYards').textContent=Math.round(remaining);$('statusLine').style.display='none';if(remaining<20){$('recClub').textContent='Putter';$('shotYards').textContent=Math.round(remaining*3);$('shotUnit').textContent=' foot putt (approx.)';drawTarget(pin,ball);return}$('shotUnit').textContent=' yard shot';const rec=recommendClub({remainingYards:remaining,clubs,from,pin:pinPx,hazards,projectAlongShot:f=>projection.project(interpolateGeo(ball,pin,f))});$('recClub').textContent=rec.club.name;$('shotYards').textContent=Math.round(Math.min(rec.club.total,remaining));if(rec.reason){$('statusLine').textContent=rec.reason;$('statusLine').style.display='block'}drawTarget(projection.unproject(rec.target),ball)}
function renderClubInputs(){const c=$('clubInputs');c.innerHTML='<span></span><span class="club-head">Carry</span><span class="club-head">Total</span>';clubs.forEach((club,i)=>{const l=document.createElement('label');l.textContent=club.name;c.appendChild(l);['carry','total'].forEach(key=>{const input=document.createElement('input');input.type='number';input.value=club[key];input.addEventListener('input',e=>{clubs[i][key]=+e.target.value||0;recommend()});c.appendChild(input)})})}
function finishHole(n){holed=true;strokeCount=n;$('strokeRow').textContent=`Holed in ${n}`;$('strokeInput').value=n;$('recClub').textContent='Holed out';$('shotYards').textContent=n;$('shotUnit').textContent=' total strokes';$('remainYards').textContent=0}
function bind(){const svg=$('hole');svg.addEventListener('click',e=>{if(holed)return;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(svg.getScreenCTM().inverse());ball=projection.unproject({x:q.x,y:q.y});strokeCount++;if(distanceYards(ball,pin)<2)return finishHole(strokeCount);updateStrokeUI();recommend()});$('resetBtn').onclick=()=>{ball={...tee};strokeCount=0;holed=false;updateStrokeUI();recommend()};$('holedBtn').onclick=()=>finishHole(Math.max(1,strokeCount+1))}
async function init(){course=await fetch(COURSE_URL).then(r=>r.json());const terrain=await fetch(TERRAIN_URL).then(r=>r.json());$('courseName').textContent=course.course;$('holeMeta').textContent=`Hole ${course.hole} · Par ${course.par} · Black tee ${course.yardages.Black} yd`;$('terrainStatus').textContent=terrain.samples.length?'Loaded':'Awaiting real elevation samples';geojson=await fetch(course.geometry.geojson).then(r=>{if(!r.ok)throw Error('Course geometry failed to load');return r.json()});const h=deriveHole18();tee=h.tee;pin=h.pin;holeGeoJSON={type:'FeatureCollection',features:h.features};const coords=collectCoordinates(holeGeoJSON);coords.push([tee.lng,tee.lat],[pin.lng,pin.lat]);projection=createProjection(coords);renderGeoJSON($('hole'),holeGeoJSON,projection);ball={...tee};hazards=[...getFeatures('water',holeGeoJSON),...getFeatures('bunker',holeGeoJSON)].map(f=>({name:featureType(f),poly:polyToScreen(f)})).filter(h=>h.poly.length);const t=projection.project(tee),g=projection.project(pin);$('teeMarker').setAttribute('x',t.x-5);$('teeMarker').setAttribute('y',t.y-4);$('pin').setAttribute('cx',g.x);$('pin').setAttribute('cy',g.y);renderClubInputs();updateStrokeUI();bind();recommend()}
init().catch(err=>{$('statusLine').textContent=`Map data error: ${err.message}`;$('statusLine').style.display='block';console.error(err)});